"""Add Audit Logs

Revision ID: c729da6263d8
Revises: 50ea41a44e17
Create Date: 2026-03-20 00:47:09.551369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c729da6263d8'
down_revision: Union[str, None] = '50ea41a44e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('decoration_codes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('qr_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_sessions_approver'))
        batch_op.drop_index(batch_op.f('ix_qr_sessions_status_expires'))

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('word_filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_filters_server_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_filters_server_id'), ['server_id'], unique=False)

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('qr_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_sessions_status_expires'), ['status', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_qr_sessions_approver'), ['approver_user_id'], unique=False)

    with op.batch_alter_table('decoration_codes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.alter_column('file_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_tokens_token_hash'), ['token_hash'], unique=True)

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
